### ISSUE TITLE
google新聞rss連結解析錯誤

### ISSUE THREAD

**Issue by milk333445** [SuYenTing/Python-web-crawler#1]
下面代碼段解析新的新聞網址的時候，會出錯
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')
newsUrl = soup.find_all('c-wiz', class_='jtabgf')[0].getText()

錯誤:
Traceback (most recent call last):
  File "C:\Users\User\web_crawler\test2.py", line 170, in <module>
    newsUrl, content = beautifulSoupNews(url=df['link'][iLink])
  File "C:\Users\User\web_crawler\test2.py", line 35, in beautifulSoupNews
    newsUrl = soup.find_all('c-wiz', class_='jtabgf')[0].getText()
IndexError: list index out of range

請問要如何解決

**Comment by SuYenTing** [comment]
@milk333445 你好!
謝謝你的回報，程式碼我已修改好[[Link]](https://github.com/SuYenTing/Python-web-crawler/commit/d7302401b5d7955020e8da9f320a33f21bf6280b)，也發現部分程式碼錯誤並一起修正。
在Google RSS連結轉原始新聞連結部分，我改用[SSujitX/google-news-url-decoder](https://github.com/SSujitX/google-news-url-decoder)提供的程式碼，新聞連結大部分都能解析出來。
你可以更新程式碼重新執行，若還有其他問題歡迎和我說，謝謝!

**Comment by milk333445** [comment]
感謝大神回復!!，收益良多，太感謝了!!
